/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function storagehandler_set_local(a: number, b: number, c: number, d: number): void;
export function storagehandler_get_local(a: number, b: number, c: number): void;
export function storagehandler_clear_local(a: number): void;
export function storagehandler_set_session(a: number, b: number, c: number, d: number): void;
export function storagehandler_get_session(a: number, b: number, c: number): void;
export function storagehandler_clear_session(a: number): void;
export function storagehandler_set_cookie(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function storagehandler_get_cookie(a: number, b: number, c: number): void;
export function storagehandler_clear_cookie(a: number): void;
export function __wbg_storagehandler_free(a: number): void;
export function utilshandler_generate_uuid(a: number): void;
export function utilshandler_is_blank(a: number, b: number): number;
export function utilshandler_format_integer(a: number, b: number): void;
export function utilshandler_format_float(a: number, b: number, c: number, d: number): void;
export function utilshandler_deep_copy(a: number, b: number): void;
export function utilshandler_capitalize_first_char(a: number, b: number, c: number): void;
export function utilshandler_hump_with_line(a: number, b: number, c: number, d: number): void;
export function utilshandler_format_phone(a: number, b: number, c: number, d: number): void;
export function __wbg_utilshandler_free(a: number): void;
export function datehandler_format(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function datehandler_get_date_by_timestamp(a: number, b: number, c: number, d: number): void;
export function datehandler_get_current_date(a: number, b: number, c: number): void;
export function __wbg_datehandler_free(a: number): void;
export function signaturehandler_encrypt(a: number, b: number, c: number): void;
export function signaturehandler_decrypt(a: number, b: number, c: number): void;
export function signaturehandler_encode(a: number, b: number, c: number): void;
export function signaturehandler_decode(a: number, b: number, c: number): void;
export function __wbg_signaturehandler_free(a: number): void;
export function is_support_wasm(a: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
